[package]
name = "diffsol"
version = "0.1.0"
edition = "2021"
description = "A library for solving ordinary differential equations (ODEs) in Rust."
license = "MIT"
license-file = "LICENSE.txt"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = ">=0.32"
nalgebra-sparse = ">=0.9"
anyhow = ">=1.0.77"
num-traits = "0.2.17"
ouroboros = "0.18.2"
serde = { version = "1.0.196", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }
