name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
    

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: ${{ github.workspace }}/.cargo
  RUSTFLAGS: -D warnings -A unused-imports
  RUSTDOCFLAGS: -D warnings
  RUST_BACKTRACE: full

jobs:
  # Check formatting.
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable --no-self-update
      - run: rustc -Vv
      - run: cargo fmt --all -- --check

  # Build documentation.
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3.3.2
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: rustdoc-${{ runner.os }}
      - run: rustup update stable --no-self-update
      - run: rustc -Vv
      - run: cargo rustdoc --all-features -- --document-private-items

  # Run linter.
  clippy:
    name: Clippy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3.3.2
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: clippy-${{ runner.os }}
      - run: rustup update stable --no-self-update
      - run: rustc -Vv
      - run: cargo clippy --all --all-targets --all-features
  unit-tests:
    name: Rust project - ${{ matrix.os }} - ${{ matrix.toolchain }} - ${{ matrix.cargo_args }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
          toolchain:
            - stable
            #- beta
            #- nightly
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
          cargo_args:
            - ''
            - '--features diffsl-llvm14'
            - '--features sundials'
          exclude:
            - toolchain: beta
              cargo_args: '--features diffsl-llvm14'
            - toolchain: nightly
              cargo_args: '--features diffsl-llvm14'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.3.2
      with:
        path: |
          ${{ env.CARGO_HOME }}
          target
        key: unit-test-${{ runner.os }}-${{ matrix.toolchain}}-${{ matrix.cargo_args }}
    - name: Set up Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      if: matrix.cargo_args == '--features diffsl-llvm14'
      with:
        version: "14.0"
    - name: Build
      run: cargo build --verbose ${{ matrix.cargo_args }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.cargo_args }}
