name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - ${{ matrix.os }} - ${{ matrix.toolchain }} - ${{ matrix.cargo_args }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
          toolchain:
            - stable
            #- beta
            #- nightly
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
          cargo_args:
            - ''
            - '--features diffsl-llvm14'
          exclude:
            - toolchain: beta
              cargo_args: '--features diffsl-llvm14'
            - toolchain: nightly
              cargo_args: '--features diffsl-llvm14'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      if: matrix.cargo_args == '--features diffsl-llvm14'
      with:
        version: "14.0"
    - name: Build
      run: cargo build --verbose ${{ matrix.cargo_args }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.cargo_args }}
